### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by scottveirs** [orcasound/orcamap-react#13]
MIT? GPL? aGPL?

**Comment by ivanoats** [comment]
MIT if ok with you @scottveirs ? Just easier and may encourage more contributions

**Comment by ivanoats** [comment]
MIT if ok with you @scottveirs ? Just easier and may encourage more contributions

**Comment by ivanoats** [comment]
Closed with https://github.com/orcasound/orcamap-react/commit/6aab990084ea58864051d038f136d5f9d480949a LMK if you'd prefer something else.
