### ISSUE TITLE
GoogleSheet Data Source 

### ISSUE THREAD

**Issue by Kunal-2001** [orcasound/orcamap-react#16]
Hello Mentors
I am new to this project and recently set up on my local machine
Can anyone tell where can I get the googlesheet data source api key. I had to raise the issue because I was not able to find any slack / discord link 
I would love to contribute in this project 
_Thank You
Kunal_

**Comment by ivanoats** [comment]
we need a way for devs to use their own google sheets. an example sheet to copy? what's the best way without sharing API keys?

**Comment by Kunal-2001** [comment]
@ivanoats 

- We can provide an example sheet to replicate and use that for development purposes
- Another way could be to create an API that calls the google sheet API and host that on the web and get access from their (not sure about this one though)

**Comment by ivanoats** [comment]
This feature was added in #26
