### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by onkar95** [orcasound/orcamap-react#37]
on running npm start after installing packages by npm install it shows error :

node:internal/modules/cjs/loader:922
throw err;
^

Error: Cannot find module 'regjsparser' 
   i had  commited  it at #36

**Comment by parthsarthiprasad** [comment]
Hello @onkar95 is your branch even with main? I cloned the repo again to ensure these errors and wasn't able to reproduce them.

**Comment by onkar95** [comment]
yes i am on main branch @parthsarthiprasad

**Comment by ivanoats** [comment]
let's help you in slack about your install error since there must be something different about your setup.

**Comment by onkar95** [comment]
thanku @ivanoats  but it get solved i had commited pull request about it  in readme file
