### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by onkar95** [orcasound/orcamap-react#39]
also after that it fails to compile
shows error:
Failed to compile.

src\App.tsx
  Line 1:26:   Delete `␍`                prettier/prettier
  Line 2:66:   Delete `␍`                prettier/prettier
  Line 3:1:    Delete `␍`                prettier/prettier
  Line 4:30:   Replace `s␍` with `⏎··s`  prettier/prettier
  Line 5:11:   Delete `␍`                prettier/prettier
  Line 6:26:   Delete `␍`                prettier/prettier
  Line 7:67:   Delete `␍`                prettier/prettier
  Line 8:23:   Delete `␍`                prettier/prettier
  Line 9:11:   Delete `␍`                prettier/prettier
  Line 10:4:   Delete `␍`                prettier/prettier
  Line 11:2:   Delete `␍`                prettier/prettier
  Line 12:1:   Delete `␍`                prettier/prettier
  Line 13:19:  Delete `␍`                prettier/prettier

src\components\MapContainer\Controls\Controls.tsx
  Line 1:26:   Delete `␍`  prettier/prettier

for every line in every file
i fixed it at #38

**Comment by onkar95** [comment]
fixing error in installation #38

**Comment by parthsarthiprasad** [comment]
Hello @onkar95 is your branch even with `main`. I cloned the repo again to ensure these errors and wasn't able to reproduce them.

Please try these steps once . Hoping you didn't change some files yourself.
`git clone https://github.com/orcasound/orcamap-react `
`cd orcamap-react`
`npm i`
`npm start`
