### ISSUE TITLE
Add router for navigation

### ISSUE THREAD

**Issue by aloksingh3112** [orcasound/orcamap-react#8]

**Comment by aloksingh3112** [comment]
#9 @ivanoats plz have a look

**Comment by Jds-23** [comment]
Hey I can definitely Add router for navigation. Please let me know the requirements - @aloksingh3112 @ivanoats @paulcretu  @watcher00090

**Comment by ivanoats** [comment]
This really depends on the work being done in #5 . 

I'm going to close this issue as it doesn't have enough description of why we need a router, what features it will enable, and what the routes would be. We have a new issue template that will help guide new feature development, so if you want to open a new issue and follow the template, go ahead. Good idea to check in and discuss on the `orcamap-react` slack channel first to flesh out the new feature idea.
